### ISSUE TITLE
Add parameter to ignore file path patterns to avoid saving matched files

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#17]
The callback will retrieve files that are loaded by Ansible throughout the execution of the playbook. This could contain files that users might not want to save, either because they are sensitive or are simply not relevant.

The implementation would be somewhat similar to that we already do with ``ignored_arguments`` and ``ignored_facts`` for ignoring specified playbook parameters and host facts.

**Comment by LaurentDumont** [comment]
I was looking at something similar. We are using a "site-configuration" that holds specific private variables. I would ideally be able to ignore that file during the upload.

I can take a crack at implementing the feature.

**Comment by dmsimard** [comment]
@LaurentDumont it would be nice to implement this indeed. Happy to review patches !

Patterning off of ignored_arguments and ignored_facts should work.. there's:
- [built-in docs](https://github.com/ansible-community/ara/blob/bd6067211fe66be0c9838c85943b97c60ed89077/ara/plugins/callback/ara_default.py#L108-L125)
- [getting parameters from the docs](https://github.com/ansible-community/ara/blob/bd6067211fe66be0c9838c85943b97c60ed89077/ara/plugins/callback/ara_default.py#L157-L158) (ansible config doc parsing magic)
- [the _get_or_create_file method](https://github.com/ansible-community/ara/blob/bd6067211fe66be0c9838c85943b97c60ed89077/ara/plugins/callback/ara_default.py#L313-L328) where the files get created.

**Comment by LaurentDumont** [comment]
I've started a quick fix for our use case - https://review.opendev.org/#/c/703276/

- It doesn't allow for pattern matching but our current need is limited to ignoring specific unique file names.
- A large majority of the Ansible files are probably going to be named `main.yml`. It could be a good idea to allow ignoring based on file path (or a keyword within the file path).

Let me know if it's an okay start! I've tested locally by modifying the callback directly and I can see the file content being sanitized.

**Comment by dmsimard** [comment]
@LaurentDumont thanks for the patch !

> A large majority of the Ansible files are probably going to be named main.yml. It could be a good idea to allow ignoring based on file path (or a keyword within the file path).

Yes, I think what we actually want are patterns instead of absolute file names because in the end, absolute file names can also be specified as patterns.
For example, a pattern of ``main.yml`` would match all the main.yml files but ``main.y[a]?ml`` would also match main.yaml.

If the users aren't interested in saving group_vars, they could specify a ``group_vars`` pattern which would prevent saving any file path where "group_vars" is present.

There are some approaches for matching strings against a list of regexes on [stack overflow](https://stackoverflow.com/questions/3040716/python-elegant-way-to-check-if-at-least-one-regex-in-list-matches-a-string) that could be worth taking a look into.

> Zuul failed once but the two errors we're somewhat nebulous and not related to my changes. I've re-run the CI and all tests passed.

It happens ¯\\_(ツ)_/¯

**Comment by dmsimard** [comment]
@LaurentDumont I was thinking we'd probably want to have some minimal testing to demonstrate that we really aren't saving files that are filtered.
I have been tinkering with an approach and was wondering what you thought about it ?

It looks like [this](https://cccf5757fefa34853463-2f18d96c12ded5c9f86090319cfc832d.ssl.cf1.rackcdn.com/663968/22/check/ansible-role-ara-api-fedora-2.9/9255619/logs/static/file/6.html) in practice and the patch for the implementation is [here](https://review.opendev.org/#/c/663968/).

I think users could come up with their own use cases for it but I'd use it for integration testing ara itself. 

For example, we could have a test where ARA would normally include a "secrets.yml" file, assert that it's there but actually empty:
```
- name: Retrieve the current playbook
    ara_playbook:
    register: playbook_query

- name: Recover secret file from ARA
  vars:
    playbook_id: "{{ playbook_query.playbook.id | string }}"
    query: "?playbook={{ playbook_id }}&path=secrets.yml"
  set_fact:
    file: "{{ lookup('ara', '/api/v1/files/' + query) }}"

# TODO: This wouldn't actually work because the file list view doesn't have the content detail
- name: Assert file
  assert:
    that:
      - file.content == "Not saved by ARA as configured by 'ignored_files'"
```
