### ISSUE TITLE
Templating values in a playbook's vars for ara_playbook_labels doesn't work

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#180]
## What is the issue ?

It doesn't look possible to use templated values in ``ara_playbook_labels`` right now, for example:
```yaml
- name: Test playbook
  hosts: localhost
  gather_facts: no
  vars:
    test_label: "test_label"
    ara_playbook_labels:
      - foo
      - "{{ test_label }}"
  tasks:
    - name: Print ara_playbook_labels
      debug:
        var: ara_playbook_labels

    - name: Retrieve the current playbook so we can inspect labels
      ara_playbook:
      register: playbook_query

    - name: Print actual playbook labels
      debug:
        msg: "{{ playbook_query.playbook.labels }}"

```

Returns:
```
> ansible-playbook -i 'localhost,' -c local tests/integration/labels.yaml
Operations to perform:
  Apply all migrations: admin, api, auth, contenttypes, db, sessions
Running migrations:
  No migrations to apply.

PLAY [Test playbook] **************************************************************************************************

TASK [Print ara_playbook_labels] **************************************************************************************
ok: [localhost] => {
    "ara_playbook_labels": [
        "foo",
        "test_label"
    ]
}

TASK [Retrieve the current playbook so we can inspect labels] *********************************************************
ok: [localhost]

TASK [Print actual playbook labels] ***********************************************************************************
ok: [localhost] => {
    "msg": [
        {
            "id": 12,
            "name": "check:False"
        },
        {
            "id": 15,
            "name": "tags:all"
        },
        {
            "id": 29,
            "name": "foo"
        },
        {
            "id": 30,
            "name": "{{ test_label }}"
        }
    ]
}

PLAY RECAP ************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

I guess we'd expect the variables to be templated by the time the play begins and where we set the labels: https://github.com/ansible-community/ara/blob/40894c7027144c4d875e5d5a97e5cfebf75ec318/ara/plugins/callback/ara_default.py#L277-L289

## What should be happening ?

It would be useful to be able to template labels so it'd be great if this worked :)
