### ISSUE TITLE
Add client-side implementation of labels

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#25]
A label is a concept exclusive to ara and it is meant to be applied to playbooks by users in order to organize playbooks in logical groups.

Some example use cases:
- Labels called ``dev``, ``staging`` and ``production`` could be applied to playbooks in order to group playbooks targetting specific environments.
- Labels called ``pre``, ``run`` and ``post`` could be used to identify which phase of a deployment the playbook ran for

Labels are simple alphanumerical strings so you could have labels targetting a bug number, a reference number, etc.

This later allows users to search for playbooks matching that label.

While labels are implemented in the API, there is no way for users to easily use them yet. I've been thinking about how this would look like in practice and it might end up being an Ansible module that looks like this:
```yaml
# Would create the label if it doesn't exist
# Description is optional but can be provided
# Appends the label to playbook.labels for state.present
# Removes the label from playbook.labels for state.absent
- name: Label this playbook
  ara_playbook_label:
    name: "{{ item }}"
    state: present
  loop:
    - pre-run
    - "{{ ansible_os_distribution }}"
    - "{{ lookup('env','USER') }}"
```
