### ISSUE TITLE
Plain content of ansible-vault encrypted files are stored

### ISSUE THREAD

**Issue by copyrights** [ansible-community/ara#385]
## What is the issue ?

Plain content of ansible-vault encrypted files are stored in "Files" section.

![grafik](https://user-images.githubusercontent.com/219009/163050168-c6e28114-7897-41f7-a2d1-130124872cbc.png)

example playbook
```yaml
---
- name: Example ansible-vault
  hosts: localhost
  vars_files:
    - some_secrets.yml
  tasks:
    - debug:
 
 ```
example some_secrets.yml (pw: 123456)
```yaml
$ANSIBLE_VAULT;1.1;AES256
66316434626265653066343439613138356131666164656438313135613333626165366533643437
6234313765393261333233663366323466333162393164620a393165613731353463373261616435
66636636376335613934666561653366363237396532323365633764393333613966383936353532
3862366239373032640a376435666530343030393166366238333532616637366566623262663034
39613535663961396139626463656335383331383034393630653632613864663063
```
## What should be happening ?
Plain content of ansible-vault encrypted files shall not be stored.
