### ISSUE TITLE
Facts won't be stored if using FQCN ansible.builtin.setup

### ISSUE THREAD

**Issue by hille721** [ansible-community/ara#397]
## What is the issue ?
Facts will not stored in Ara if using the FQCN `ansible.builtin.setup`.

Example playbook:
```
---
- name: Gather Facts Bug
  hosts: localhost
  gather_facts: false

  tasks:
    - name: facts won't be stored in ara
      ansible.builtin.setup:
```

Facts are not in Ara:
![image](https://user-images.githubusercontent.com/38468371/180397571-797e68af-d43b-46b9-9677-7686d42a3f3e.png)

## What should be happening ?
It should work with FQCN the same way as it works for the short notation

Example playbook which works:

```
---
- name: Gather Facts Bug
  hosts: localhost
  gather_facts: false

  tasks:
    - name: facts will be stored in ara
      setup:
```

## Versions

Issue verified for:

* ara 1.5.8 & ansible-core 2.12.6 
* ara 1.5.8 & ansible-core 2.13.1
