### ISSUE TITLE
Running ara_api playbook fails on install_ara

### ISSUE THREAD

**Issue by rndmh3ro** [ansible-community/ara#43]
# Problem

Installing ara on Ubuntu 18.04 with: 
```bash
> ubuntu:~/ara-1.0.0b1/playbooks$ cat hosts
127.0.0.1
> ansible-playbook -i hosts ara_web.yaml -K
```

fails with: 

```bash
TASK [ara_api : Prepare git repository for ara] **********************************************************************
changed: [127.0.0.1]

TASK [ara_api : Install ara] *****************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to find required executable virtualenv in paths: /usr
/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"}
        to retry, use: --limit @/home/basti/ara-1.0.0b1/playbooks/ara_api.retry

PLAY RECAP ***********************************************************************************************************
127.0.0.1                  : ok=12   changed=5    unreachable=0    failed=1
```

# Resolution

Change the install ara task to look like this.
Since Python 3 is required for ara and on Ubuntu the binary `virtualenv` does not exist, I guess this should be fine. However I did not test in on other operating systems. I can provide a PR for it.

```yaml
- name: Install ara
  pip:
    name: "{{ ara_api_source_checkout }}[server]"
    state: present
    virtualenv: "{{ ara_api_venv | bool | ternary(ara_api_venv_path, omit) }}"
    #virtualenv_python: python3
    virtualenv_command: "/usr/bin/python3 -m venv"
```

# Additional data

ARA-release: `1.0.0b1`

OS:
```
VERSION="18.04.2 LTS (Bionic Beaver)"
```

Python:
```
ubuntu:~/ara-1.0.0b1/playbooks$ python --version
Python 2.7.15rc1
ubuntu:~/ara-1.0.0b1/playbooks$ which python
/usr/bin/python
```
