### ISSUE TITLE
pytz.exceptions.UnknownTimeZoneError: None

### ISSUE THREAD

**Issue by rndmh3ro** [ansible-community/ara#45]
# Problem

Running ara on Ubuntu 18.04 fails with nginx and gunicorn.
When opening the URL via nginx, I get a Internal Server Error and the following exception in the log: https://gist.github.com/rndmh3ro/2117d0d5dc286f38fe849788709ad42e

However when opening ara on port 3000 it works.

Installed with the playbook:
```
- name: Install ARA with default settings
  hosts: all
  gather_facts: yes
  vars:
    ara_api_frontend_server: nginx
    ara_api_wsgi_server: gunicorn
    ara_api_fqdn: 172.24.126.194
    ara_api_allowed_hosts:
      - localhost
  roles:
    - ara_api
    - ara_web
```

# Resolution
I don't know. I tried fiddling with the TIME_ZONE parameter but that didn't help.

# Additional data

ARA-release: `1.0.0b1`

OS:
```
VERSION="18.04.2 LTS (Bionic Beaver)"
```

Timezone:
```
(virtualenv) ubuntu:~/ara-1.0.0b1/playbooks$ cat /etc/timezone
Europe/Berlin
```
