### ISSUE TITLE
callback plugin creates broken folder in the current working directory

### ISSUE THREAD

**Issue by nlvw** [ansible-community/ara#469]
## What is the issue ?
When running any playbook with ARA callback plugin enabled a malformed directory is created in the same folder as ansible.cfg.  This only happens when ARA (1.6.0) is enabled.

```console
$ ls -1
ansible.cfg
'{{ ANSIBLE_HOME ~ "'
bootstrap.sh
collections
container.def
inventory
playbooks
README.md
requirements.txt
roles
web_services

$ tree \{\{\ ANSIBLE_HOME\ ~\ \"/
{{ ANSIBLE_HOME ~ "/
└── tmp" }}
```

If I delete the directory, disable ARA, and run playbook again it isn't recreated.  Then when I enable ARA the same playbook will create that strange directory.

playbook
```yaml
---

- name: "Test Ansible Connection"
  hosts: "{{ cplay_hosts | default('all') }}"
  become: false
  strategy: linear
  gather_facts: no
  tasks:
    - name: connection test
      ping:
  post_tasks:
    - name: stop ssh client persistant connection
      meta: reset_connection
```

## What should be happening ?
Additional directories should not be created in the same folder as ansible.cfg as this can make git mad.

## Software Versions
Ansible = 7.1.0 (Core = 2.14)
OS = Fedora 37
Python = 3.11
ARA = 1.6.0
Install Source = pip
