### ISSUE TITLE
Having trouble getting ARA working in ansible-semaphore alpine docker container

### ISSUE THREAD

**Issue by samcro1967** [ansible-community/ara#488]
Below is what I have tried to get ARA working with ansible-semaphore.

1.  Added environment variables to Semaphore docker compose for `ANSIBLE_CALLBACK_PLUGINS`, `ARA_API_CLIENT`, & `ARA_API_SERVER`.
2. Installed pip3 and ARA w/o server API using a custom Dockerfile in the semaphore container.
3. Confirmed with `ansible-config dump` that `ANSIBLE_CALLBACK_PLUGINS` is seen by ansible.
4. Confirmed with echo from inside the container that environment variables `ARA_API_CLIENT` & `ARA_API_SERVER` are present.
5. Configured ARA to listen on 192.168.1.104 in /opt/ara/settings.yaml.
6. Ran playbook with `--vvv` and waited until successful completion.
7. Browsed to ARA reporting URL and no playbook executions, tasks, or hosts are present.

**Dockerfile**
```
FROM semaphoreui/semaphore:latest

USER root
RUN apk add rsync py3-pip
user semaphore
RUN pip install git+https://github.com/ansible-community/ara
ENV PATH="$PATH:/home/semaphore/.local/bin/"
```
<sumary>**Docker Compose**</summary>
<details>

```
  ara-api:
    hostname: ara-api
    image: recordsansible/ara-api:latest
    container_name: ara-api
    restart: always
    ports:
      - 9450:8000
    volumes:
      - ${docker}/ara-api:/opt/ara
    tty: true  
semaphore:
    hostname: semaphore
    image: osu.registry:5000/user/semaphore:latest #semaphoreui/semaphore:latest
    container_name: semaphore
    restart: unless-stopped
    environment:
      - SEMAPHORE_DB_USER=user
      - SEMAPHORE_DB_PASS=password
      - SEMAPHORE_DB_HOST=mysql
      - SEMAPHORE_DB_PORT=3306
      - SEMAPHORE_DB_DIALECT=mysql
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=password
      - SEMAPHORE_ADMIN_NAME=user
      - SEMAPHORE_ADMIN_EMAIL=user@doamin.net
      - SEMAPHORE_ADMIN=user
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=<redacted>
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_CALLBACK_PLUGINS=$(python3 -m ara.setup.callback_plugins)
      - ARA_API_CLIENT=http
      - ARA_API_SERVER=http://192.168.1.104:9450
    ports:
      - 3100:3000
    volumes:
      - ${docker}/semaphore/temp:/tmp/semaphore/
      - ${docker}/semaphore/ansible/ansible.cfg:/etc/ansible/ansible.cfg
      - ${docker}/semaphore/config/config.json:/etc/semaphore/config.json
      - ${docker}/ansible:/ansible
      - /home/user:/home/user
    depends_on:
      - mysql
```
</details>

I setup the ARA client on my localhost and ran ansible from the host.  It reports as expected to the dockerized ARA API.  I suspect at this point the install of ARA client in the semaphore container is not working correctly.  `ara playbook list` does not work without adding `/home/semaphore/.local/bin/` to the path.  Thinking other dependencies may be needed for Alpine.

I changed `ANSIBLE_CALLBACK_PLUGINS` to `/home/semaphore/.local/lib/python3.10/site-packages/ara/plugins/callback` and I am now seeing it try to load when a task runs.  Using the environment variable it was translating to `'/home/semaphore/$(python3 -m ara.setup.callback_plugins)'`

Semaphore task output now shows the following during the ansible execution with `--vvv` enabled.
```
[WARNING]: Skipping plugin (/home/semaphore/.local/lib/python3.10/site-
11:23:03 AM
packages/ara/plugins/callback/ara_default.py) as it seems to be invalid: No
11:23:03 AM
module named 'ara'
```

**Ansible and Python Versions**
```
ansible [core 2.13.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/semaphore/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/semaphore/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.11 (main, Apr  6 2023, 01:17:26) [GCC 11.2.1 20220219]
  jinja version = 3.0.3
  libyaml = True
```

**pip3 list | grep ara**
```
ara                1.6.1
```
