### ISSUE TITLE
no_log on individual loop items

### ISSUE THREAD

**Issue by nlvw** [ansible-community/ara#489]
A cool, but probably unknown feature, of looping in Ansible is that you can set `no_log` on a per item basis.  Unfortunately ARA doesn't recognize this and discards the entire tasks output instead of just the loop/item marked with `no_log`.

The benefit of the below is you get logs for loops where no password is specified or a locked/empty password */! is specified.  This helps troubleshooting or viewing things like AD user home creations, local accounts without passwords, and so on.

It would be nice if ARA could selective hide loop output based on `no_log` value the same as ansible.

Ansible Task
```yaml
- name: set local and adusers users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    uid: "{{ item.uid | default(omit) }}"
    password: "{{ item.password | default(omit) }}" # result is masked/hidden
    update_password: "{{ item.update_password | default(omit) }}"
    password_lock: "{{ item.password_lock | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    create_home: "{{ item.create_home | default(omit) }}"
    move_home: "{{ item.move_home | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    umask: "{{ item.umask | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
    local: "{{ item.local | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    remove: "{{ item.remove | default(omit) }}"
    expires: "{{ item.expires | default(omit) }}"
  when:
    - item.name is defined
    - item.name | length > 0
  loop: "{{ lookup('community.general.merge_variables', '^users_users($|_.*$)', pattern_type='regex', initial_value=[]) }}"
  loop_control:
    label: "{{ item.name }}"
  no_log: "{{ true if ((item.password is defined) and (item.password != '*') and (item.password != '!')) else false }}"
```

Console Output (red marked out names displayed correctly and 'None' denotes a `no_log` item)
<img width="528" alt="image" src="https://github.com/ansible-community/ara/assets/5723368/7931cda7-5c1d-4629-8d44-ee571b6551e7">

ARA Task Result:
<img width="853" alt="image" src="https://github.com/ansible-community/ara/assets/5723368/59919d80-c965-4ff2-94bd-67bea30579ba">
