### ISSUE TITLE
Server Error (500), cannot find logs

### ISSUE THREAD

**Issue by bendem** [ansible-community/ara#576]
## What is the issue ?

I just upgraded from 1.7.0 to 1.7.2.

I'm getting random `Server Error (500)` errors and playbooks fail to record (at the start, so I get nothing in ara, or during the play, so it's missing tasks). I tried looking in the logs and all I see is the access log.
![image](https://github.com/user-attachments/assets/2304f8a5-ae0c-4e62-b67b-9450d2fabb5a)

I've played with the command to add all possible variations of `--error-log -`, `--capture-output`, setting `ARA_LOGGING`, `ARA_DEBUG` and `ARA_LOG_LEVEL`, tried logging to file and to console, propagate or not, I get no logs at all, only the access log from gunicorn (the log file is created, so my logging config is read at least).

## What should be happening ?

I should see the error in my console or log file and be able to debug further.

## What I'm running

I'm running [docker.io/recordsansible/ara-api@sha256:178780b2ad10484bbdf17a7cbf57dcdf77f362e5c6f76d8df8aa99ee125b4dfa](https://hub.docker.com/layers/recordsansible/ara-api/centos9-pypi-latest/images/sha256-178780b2ad10484bbdf17a7cbf57dcdf77f362e5c6f76d8df8aa99ee125b4dfa?context=explore) (centos9-pypi-latest with 1.7.2) in docker on RockyLinunx 8.

My docker-compose looks like this:

```yml
#
# {{ ansible_managed }}
#

networks:
  ara:
    name: ara

services:
  ara-api:
    image: {{ ara_image }}
    # command: "bash -c '/usr/local/bin/ara-manage migrate && python3 -m gunicorn --workers=4 --access-logfile - --error-logfile - --capture-output --bind 0.0.0.0:8000 ara.server.wsgi'"
    # user: 1000:1000
    container_name: ara-api
    hostname: ara-api
    domainname: vdl.intra
    restart: unless-stopped
    networks:
      - ara
    environment:
      # Set the secret key to avoid django trying to modify its own files
      - ARA_SECRET_KEY={{ lookup('vdl.devops.password', 'secret_key') }}
      - ARA_EXTERNAL_AUTH=true
      - ARA_READ_LOGIN_REQUIRED=false
      - ARA_WRITE_LOGIN_REQUIRED=false
      - ARA_ALLOWED_HOSTS=['{{ ara_host }}']
      - ARA_CORS_ORIGIN_WHITELIST=['{{ ara_url }}']
      - ARA_CSRF_TRUSTED_ORIGINS=['{{ ara_url }}']

      - ARA_DATABASE_ENGINE=django.db.backends.postgresql
      # @cleanup-pg-cluster
      - ARA_DATABASE_HOST={{ pg_cluster_host }}
      - ARA_DATABASE_PORT={{ pg_cluster_port }}
      - ARA_DATABASE_NAME=ara
      - ARA_DATABASE_USER=ara
      - ARA_DATABASE_PASSWORD={{ lookup('vdl.devops.password', 'database_password') }}
      - ARA_DATABASE_CONN_MAX_AGE=120
      - 'ARA_DATABASE_OPTIONS=@json {"sslrootcert": "/etc/ssl/vdl-root-ca2.pem"}'
      - PGSSLROOTCERT=/etc/ssl/vdl-root-ca2.pem

      # - 'ARA_LOGGING=@json {"disable_existing_loggers":false,"formatters":{"normal":{"format":"%(asctime)s %(levelname)s %(name)s: %(message)s"}},"handlers":{"console":{"class":"logging.StreamHandler","formatter":"normal","level":"DEBUG","stream":"ext://sys.stdout"},"file":{"class":"logging.FileHandler","formatter":"normal","level":"DEBUG","filename":"/opt/ara/ara.log"}},"loggers":{"ara":{"handlers":["console","file"],"level":"DEBUG","propagate":0}},"level":"DEBUG","version":1}'
      # - ARA_LOG_LEVEL=DEBUG
      # - PYTHONUNBUFFERED=1

      - ARA_PAGE_SIZE=50
      - ARA_TIME_ZONE=Europe/Brussels
    volumes:
      - "{{ ca_cert_directory }}/vdl-root-ca2.pem:/etc/ssl/vdl-root-ca2.pem:ro"
```
