### ISSUE TITLE
ara_playbook_labels not added

### ISSUE THREAD

**Issue by NiceRath** [ansible-community/ara#581]
## What is the issue ?
We try to pass some inventory-specific & group-specific labels to the ARA-client.

To ensure these are set as expected - we assert it inside our playbook:

```yaml
- name: Test
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - ansible.builtin.assert:
        that:
          - ara_playbook_labels is defined
          - ara_playbook_labels | length > 0
```

But when I check-out the `play_vars` - the variable is not set?
```python3
...
raise ValueError("ara_playbook_labels" in play_vars, play_vars.keys())
if "ara_playbook_labels" in play_vars:
    ...
```
At: https://github.com/ansible-community/ara/blob/master/ara/plugins/callback/ara_default.py#L511

It Prints:

```
(False, dict_keys([<USER-SPECIFIC-VARS-REDACTED>, 'playbook_dir', 'ansible_playbook_python',
'ansible_config_file', 'ansible_role_names', 'ansible_play_role_names', 'ansible_dependent_role_names', 'role_names',
'ansible_play_name', 'groups', 'ansible_play_hosts_all', 'ansible_play_hosts', 'ansible_play_batch', 'play_hosts', 'omit',
'ansible_version', 'ansible_check_mode', 'ansible_diff_mode', 'ansible_forks', 'ansible_inventory_sources',
'ansible_skip_tags', 'ansible_limit', 'ansible_run_tags', 'ansible_verbosity', 'hostvars']))
```

When in the play_vars - the variable exists. But it seems to be nested under `hostvars` .

```python3
...
for k, v in play_vars.items():
    if v is not None and str(v).find("ara_playbook_labels") != -1:
        raise ValueError(k, v)
...
```

## What should be happening ?

I would expect the variable to work as documented: https://ara.readthedocs.io/en/latest/ansible-plugins-and-use-cases.html#playbook-names-and-labels

Two solutions come to my mind:
* Either update the documentation, so it mentions that inventory-vars DO NOT work.
* Or check the hostvars for `ara_playbook_labels`
