### ISSUE TITLE
An Ansible action module to manage a playbook's ara labels

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#596]
## What is the idea ?

ara's playbook labels are currently set via environment/configuration/ansible ([docs](https://ara.readthedocs.io/en/latest/ansible-plugins-and-use-cases.html#playbook-names-and-labels)).

It could be useful to manipulate a playbook's labels like this:
```yaml
- name: Add labels to the running playbook
  ara_label:
    state: present
    labels:
      - dev
      - {{ ansible_facts['os_family'] }}

- name: Add labels to a specific playbook
  ara_label:
    state: present
    playbook_id: 21
    labels:
      - "state:deployed"
      - "python:{{ ansible_facts['python_version'] }}"

- name: Remove labels from the running playbook (if they exist)
  ara_label:
    state: absent
    labels:
      - running
```
