### ISSUE TITLE
API not receiving hosts. 

### ISSUE THREAD

**Issue by adahlmanpinterest** [ansible-community/ara#87]
## What component is this about ?
API Client

## What is your ARA installation like ?
Ara api is installed on an its own aws instance behind an ELB. 
The ara-web server is able to talk to the api webserver , ara.pinadmin.com and araweb.pinadmin.com. 

The elb is pointing from 80-8000. And allowing all traffic from our RFC 1819 space. 

## What is happening ?
Currently running test ansible runs and the API server isn't picking up the request. Here is the ansible.cfg:

```
[defaults]
inventory = /etc/ansible/inventory/production.yaml
remote_tmp = /etc/ansible/tmp
local_tmp = /etc/ansible/tmp
log_path = /var/log/ansible.log
callback =  ara
callback_type = notification
[ara]
api_client = http
api_server = http://ara.pinadmin.com
api_username = joe
api_password = joe12345678
api_timeout = 15
ignored_facts = '["ansible_env", "ansible_all_ipv4_addresses"]'
ignored_arguments = '["extra_vars", "vault_password_files"]'
```

playbook:
```
 - name: Run playbook for all hosts
    hosts: all 
  connection: local
  vars_files:
    - /etc/ansible/vars/basevars.yml
  become: true
  vars:
    ara_playbook_name: base
    ara_playbook_labels:
        - base-test
  roles:
   - logrotate
```

settings.yaml 
```default:
  ALLOWED_HOSTS: !!python/object/new:box.BoxList
    listitems:
    - ::1
    - 127.0.0.1
    - localhost
    - ara.mars.pinadmin.com
    - ara.pinadmin.com
    state:
      box_class: &id001 !!python/name:box.Box ''
      box_options: {}
      box_org_ref: 140525303662472
  BASE_DIR: /opt/ara/.ara/server
  CORS_ORIGIN_ALLOW_ALL: true
  CORS_ORIGIN_WHITELIST: !!python/object/new:box.BoxList
    listitems:
    - http://127.0.0.1:8000
    - http://ara.pinadmin.com:8000
    - http://ara.mars.pinadmin.com:8000
    - http://araweb.pinadmin.com:3000
    - http://araweb.mars.pinadmin.com:3000
    - http://araweb.pinadmin.com
    - http://araweb.mars.pinadmin.com
    - http://10.245.66.205:3000/
```

 The security groups are allowing traffic in as I'm able to curl the api server from all my servers.  Am I missing anything Ansible wise that would cause these requests to not reach the api?

## What should be happening ?
Ansible playbooks should be reporting to the API.
